# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/danie/w5500StateMachine/w5500StateMachine.srcs/sources_1/ip/axis_data_fifo_16_times_8bit/axis_data_fifo_16_times_8bit.xci
# IP: The module: 'axis_data_fifo_16_times_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/w5500StateMachine/w5500StateMachine.gen/sources_1/ip/axis_data_fifo_16_times_8bit/axis_data_fifo_16_times_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_16_times_8bit'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/danie/w5500StateMachine/w5500StateMachine.srcs/sources_1/ip/axis_data_fifo_16_times_8bit/axis_data_fifo_16_times_8bit.xci
# IP: The module: 'axis_data_fifo_16_times_8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/danie/w5500StateMachine/w5500StateMachine.gen/sources_1/ip/axis_data_fifo_16_times_8bit/axis_data_fifo_16_times_8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_16_times_8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
